services:

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - rede-microservicos
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 10s
      timeout: 5s
      retries: 6

  catalogo-produtos:
    build:
      context: ./catalogo-produtos
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - rede-microservicos

  pedidos-service:
    build:
      context: ./pedidos-service
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    depends_on:
      - eureka-server
      - catalogo-produtos
    environment:
      - SERVER_PORT=8200
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - rede-microservicos

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - catalogo-produtos
      - pedidos-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - rede-microservicos

networks:
  rede-microservicos:
    driver: bridge
