version: "3.8"

services:

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - rede-microservicos

  catalogo-produtos:
    build:
      context: ./catalogo-produtos
      dockerfile: Dockerfile
    ports:
      - "8201:8201"
    depends_on:
      - eureka-server
    networks:
      - rede-microservicos

  servico-pedidos:
    build:
      context: ./servico-pedidos
      dockerfile: Dockerfile
    ports:
      - "8202:8202"
    depends_on:
      - eureka-server
      - catalogo-produtos
    networks:
      - rede-microservicos

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - catalogo-produtos
      - servico-pedidos
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - rede-microservicos

networks:
  rede-microservicos:
    driver: bridge
